language: cpp

compiler:
  - cmake

os:
  - osx:
    - osx_image: xcode6.4

before_install:
  - brew update
  - brew tap F1ash/homebrew-qt-virt-manager
  - brew install libvirt libvirt-glib
  - brew tap jeffreywildman/homebrew-virt-manager
  - brew install usbredir spice-protocol
  - brew install qt5 glib qtermwidget x11vnc
 

script:
  - cmake -DBUILD_QT_VERSION=5 -DWITH_LIBCACARD=0 -DBUILD_TYPE=Debug -DUSE_SPICE_AUDIO=1 . && make all

branches:
  only:
  - master
  
env:
  global:
  - LANG="en_US.UTF-8"

