language: cpp

osx_image:
  xcode7.2
  
compiler:
  - cmake

os:
  - osx

before_install:
  - brew update
  - brew tap jeffreywildman/homebrew-virt-manager
  - brew tap F1ash/homebrew-qt-virt-manager
  - brew install qt5 qtermwidget x11vnc libvirt-glib usbredir spice-protocol
 

script:
  - cmake -DBUILD_QT_VERSION=5 -DWITH_LIBCACARD=0 -DBUILD_TYPE=Debug \
    -DUSE_SPICE_AUDIO=1 -DCMAKE_PREFIX_PATH=$(brew --prefix qt5) . && make all

branches:
  only:
  - master
  
env:
  global:
  - LANG="en_US.UTF-8"

