language: cpp

compiler:
  - cmake

os:
  - osx

before_install:
  - brew update
  - brew tap jeffreywildman/homebrew-virt-manager
  - brew tap F1ash/qt-virt-manager/HomeBrew
  - brew install libvirt libvirt-glib usbredir spice-protocol qtermwidget x11vnc
 

script:
  - cmake -DBUILD_QT_VERSION=5 -DWITH_LIBCACARD=0 -DBUILD_TYPE=Debug -DUSE_SPICE_AUDIO=1 . && make all

branches:
  only:
  - master
  
env:
  global:
  - LANG="en_US.UTF-8"

