language: cpp

compiler:
  - cmake

os:
  - osx

before_install:
  - brew update && brew install qt5 libvirt qtermwidget5 spice-vdagent \
    libvncserver glibc-headers spice-protocol spice-glib

script:
  - cmake -DBUILD_QT_VERSION=5 -DWITH_LIBCACARD=0 -DBUILD_TYPE=Debug -DUSE_SPICE_AUDIO=1 . \
    && make all

branches:
  only:
  - master
  
env:
  global:
  - LANG="en_US.UTF-8"

