language: cpp

osx_image:
  xcode7.2
  
compiler:
  - cmake

os:
  - osx

before_install:
  - brew update
  - brew tap jeffreywildman/homebrew-virt-manager
  - brew tap F1ash/homebrew-qt-virt-manager
  - brew install qt-virt-manager
 

script: true

branches:
  only:
  - master
  
env:
  global:
  - LANG="en_US.UTF-8"

