title: Qt Virtual machines manager
description: qt virtual machine manager libvirt spice vnc lxc kvm qemu xen openvz vbox vmware
google_analytics: 
show_downloads: true
theme: jekyll-theme-minimal

gems:
  - jekyll-mentions
